version: '3.8'

services:
  fastapi:
    build:
      context: ./be
      args: 
        ENV: prod
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

  nextjs:
    build:
      context: ./fe
      args: 
        ENV: prod
    ports:
      - "3000:3000"
    env_file:
      - .env