version: '3.8'

services:
  postgres:
    build:
      context: ./db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  
  fastapi:
    build:
      context: ./be
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./be:/app
    env_file:
      - .env
