version: '3.8'

services:
  fastapi:
    build:
      context: ./be
      args: 
        ENV: dev
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./be:/app

  nextjs:
    build:
      context: ./fe
      args: 
        ENV: dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./fe:/app