name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy using sshpass
        env:
          DROPLET_PASSWORD: ${{ secrets.DROPLET_PASSWORD }}
        run: |
          sshpass -p "${DROPLET_PASSWORD}" ssh -o StrictHostKeyChecking=no root@146.190.234.229 'cd ~/zoo && git pull origin main && ./build-prod.sh'
