name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Login & Deploy
        env:
          DROPLET_PASSWORD: ${{ secrets.DROPLET_PASSWORD }}
        run: |
          sshpass -p "${DROPLET_PASSWORD}" ssh root@68.183.9.57
